AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: RoboFlightMonitorService as Lambda.

Resources:
  RoboFlightMonitorAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/RoboFlightMonitorService-1.0.jar
      Handler: nl.cyberworkz.roboflightmonitor.StreamLambdaHandler
      Runtime: java8
      Environment:
        Variables:
          RFM_APP_KEY: 0
          RFM_APP_ID: 0
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      MemorySize: 512      
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            
  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - RoboFlightMonitorAPI
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RoboFlightMonitorAPI
      Principal: apigateway.amazonaws.com